name: Sonar Checks
on:
  push:
    branches:
      - main
      - development
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # TODO -> Install dependencies and run tests
      - name: Install dependencies
        run: npm install
      - name: Test and coverage
        run: npx jest --coverage
      - name: SonarCloud Scan
        id: scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}

      # TODO -> Send SonarCloud output to Slack
        # Tried to parse as an Object
      # - name: Echo Output SonarCloud
      #   run: |
      #     echo ${{ steps.scan.outputs }} > output.json
      #     cat output.json

      #   # Set env variable with the output so then I can send it to Slack
      # - name: Set Output to env variable
      #   shell: bash
      #   run: echo "OUTPUT_SONAR=$(echo ${{ steps.scan.outputs }})" >> $GITHUB_ENV

      # - name: Echo Output SonarCloud From Env
      #   shell: bash
      #   run: echo ${{ toJson(env.OUTPUT_SONAR) }}

  # messageSlack:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Notification Slack
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_CHANNEL: github
  #         SLACK_TITLE: Backend
  #         SLACK_USERNAME: BotRepo
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         SLACK_MESSAGE: ${{ env.OUTPUT_SONAR }}
